  name: 'load and cache action'
  description: 'load code and cache code action'
  inputs:
    caching:
      description: "the value for implement caching or not "
      required: false
      default: 'true'

    name:
      description: "name"
      required: true
      default: 'yazan'
      type: String

  runs:
    using: 'composite'
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle dependencies
        if: inputs.caching == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: output information
        run: echo "the name is ${{ inputs.name }}"
        shell: bash